### ISSUE TITLE
Way to efficiently get score of potential new structure

### ISSUE THREAD

**Issue by wolfg259** [JoelvanIngen/MinProg-AH#6]
Currently, if an algorithm depends on the score that a change to a protein structure will generate, there is no way of obtaining the score without either setting the structure of the main protein to the new structure, saving the previous order and calculating the score, or generating a new protein object to compare scores. An efficient score checker, perhaps outside of the Protein class, could be constructed. It could take just a sequence and an order as inputs.

**Comment by JoelvanIngen** [comment]
For reference, creating a Protein, setting an order and computing a score (repeat process 50_000 times) takes about 30 seconds, which is indeed too slow for any serious algorithm.

**Comment by JoelvanIngen** [comment]
27f36711730faec4a411abcbebb1f6caac97f822 adds a 35x ~ 40x speedup for the usecase of measuring bond score of a sequence and order

**Comment by JoelvanIngen** [comment]
It seems when disabling profiling, the speedup drops to ~25x, still a good speedup
