### ISSUE TITLE
Add attribute to Protein that allows direct access to directions

### ISSUE THREAD

**Issue by wolfg259** [JoelvanIngen/MinProg-AH#9]
Currently, all directions of a protein ordering have to iteratively be taken from the respective Node objects. This is slow, and a form of direct access to all directions would allow for quicker algorithm execution.

**Comment by wolfg259** [comment]
Fixed in commit [8092da9](https://github.com/JoelvanIngen/MinProg-AH/commit/8092da94a713dd06d63d9d3c2eb3d95dcf6534af) by adding directly accessible attribute order to Protein

**Comment by JoelvanIngen** [comment]
TODO:
- Update Protein.order when single node changes direction
